/** ISO 3166-1 alpha-2 codes used by [flag-icons](https://github.com/lipis/flag-icons) */
const TEAM_FLAG_CODES: Record<string, string> = {
	mex: 'mx',
	kor: 'kr',
	rsa: 'za',
	cze: 'cz',
	can: 'ca',
	sui: 'ch',
	qat: 'qa',
	bih: 'ba',
	bra: 'br',
	mar: 'ma',
	sco: 'gb-sct',
	hai: 'ht',
	usa: 'us',
	par: 'py',
	aus: 'au',
	tur: 'tr',
	ger: 'de',
	ecu: 'ec',
	civ: 'ci',
	cur: 'cw',
	ned: 'nl',
	jpn: 'jp',
	tun: 'tn',
	swe: 'se',
	bel: 'be',
	irn: 'ir',
	egy: 'eg',
	nzl: 'nz',
	esp: 'es',
	uru: 'uy',
	ksa: 'sa',
	cpv: 'cv',
	fra: 'fr',
	sen: 'sn',
	nor: 'no',
	irq: 'iq',
	arg: 'ar',
	aut: 'at',
	alg: 'dz',
	jor: 'jo',
	por: 'pt',
	col: 'co',
	uzb: 'uz',
	cod: 'cd',
	eng: 'gb-eng',
	cro: 'hr',
	pan: 'pa',
	gha: 'gh'
};

export function getTeamFlagCode(teamId: string): string | null {
	return TEAM_FLAG_CODES[teamId] ?? null;
}
